# Generated by Django 3.1.1 on 2020-09-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
