# Generated by Django 3.1.1 on 2020-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200921_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
